fix: remove figgy-pudding
npm/libnpmpublish pull request #9
Opened 2020-02-24 21:47 UTC by claudiahdz

Removes figgy-pudding and drops support for Node 6 & 8.

2020-02-25 20:44 UTC, isaacs requested changes
We need to figure out what to do about `publishConfig.tag` and the `tag` vs `defaultTag` usage throughout this.  Another option I hadn't considered was to just let them be aliases in the npm.flatOptions object, but that should probably be documented if so.

2020-02-25 20:44 UTC, isaacs commented on publish.js
> +      tag: 'latest',
This should be `defaultTag`.  (Moved to that canonical name to fit with the usage in npm-pick-manifest and friends.)

2020-02-25 20:44 UTC, isaacs commented on publish.js
>  function publish (manifest, tarball, opts) {
Need a default value for these function calls to preserve how the FP function would handle missing opts.  `, opts = {})`

2020-02-25 20:44 UTC, isaacs commented on publish.js
> +      ...manifest.publishConfig,
Oh.... this is interesting...

The `publishConfig` option in package.json traditionally used the config names that you'd put in npmrc or on the command line. (Ie, the `css-case` variants and some non-canonical names.)

This is relevant because it means that `"publishConfig": { "tag": "next" }` will set `opts.tag` instead of `opts.defaultTag`.

So, I think we have to add a method in here to convert any known aliases that are relevant options for publish.  The alternative is that we switch from `defaultTag` to `tag` everywhere (which is a pretty extensive change), or have users put `defaultTag` in publishConfig instead of `tag` (which is a pretty big user footgun).

2020-02-25 20:44 UTC, isaacs commented on publish.js
>    manifest._nodeVersion = process.versions.node
Should this be `opts.nodeVersion`?  We allow overriding the effective node version for installation, but maybe we ought not to for publishing?

2020-02-25 20:44 UTC, isaacs commented on publish.js
> +  const { access, tag: _tag, algorithms } = opts
tag -> defaultTag here as well

2020-02-25 20:44 UTC, isaacs commented on publish.js
> +  const tag = manifest.tag || _tag
Wait, what?  You can put a `tag` field in package.json, and it'll use that??  I've been doing `publishConfig: { tag: ... }` forever like an animal.  TIL!

2020-02-25 20:44 UTC, isaacs commented on publish.js
> +  const tag = manifest.tag || _tag
That is not even slightly documented in [`npm help package.json`](https://docs.npmjs.com/files/package.json).

2020-02-25 20:44 UTC, isaacs commented on publish.js
>      readme: manifest.readme || ''
We _might_ be able to stop doing this, since we only serve the readme that's in the actual tarball nowadays anyway.  Would make publishes go faster.

2020-03-04 00:36 UTC, claudiahdz commented
Closing in favor of: https://github.com/npm/libnpmpublish/pull/10

2020-03-04 00:36 UTC, closed without merging